role: Agent

service:
  enabled: false

customConfig:
  data_dir: "/vector-data-dir" # <-- Add this line to fix the crash

  sources:
    kubernetes_logs:
      type: kubernetes_logs
      exclude_paths_glob_patterns:
        - "/var/log/pods/kube-system_*/**"
        - "/var/log/pods/vector_*/**"

  transforms:
    parse_json:
      type: remap
      inputs: ["kubernetes_logs"]
      source: |-
        parsed, err = parse_json(.message)
        if err == null {
          . = merge!(., parsed)
          del(.message)
        }

        # Output just the suffix name
        if .kubernetes.pod_namespace == "tenant-a" {
          .tenant_suffix = "tenant-a"
        } else if .kubernetes.pod_namespace == "ecommerce" {
          .tenant_suffix = "ecommerce"
        } else {
          abort
        }

  sinks:
    local_zincsearch:
      type: elasticsearch
      inputs: ["parse_json"]
      endpoints: ["http://zincsearch.logging.svc.cluster.local:4080/es/"]
      mode: bulk

      bulk:
        # The hardcoded 'explicit-' prefix satisfies Vector's security check
        index: 'explicit-{{ "{{ tenant_suffix }}" }}'
      auth:
        strategy: basic
        user: "admin"
        password: "VectorAdmin123!"
      healthcheck:
        enabled: false
